const produtos = [
  {
    nome: "Banana",
    preco: 4,
    secao: "Hortifruti",
    categoria: "fruta",
    img: "./src/img/banana.png",
    promocao: true,
    precoPromocao: "1.00",
    componentes: ["Potássio", "Vitamina B6", "Vitamina C", "Folatos"],
  },
  {
    nome: "Morango",
    preco: 7,
    secao: "Hortifruti",
    categoria: "fruta",
    img: "./src/img/morango.png",
    promocao: false,
    precoPromocao: "0",
    componentes: ["Fibras", "Vitamina C", "Cálcio", "Ferro", "Potássio"],
  },
  {
    nome: "Maçã",
    preco: 4,
    secao: "Hortifruti",
    categoria: "fruta",
    img: "./src/img/maca.png",
    promocao: true,
    precoPromocao: "1.50",
    componentes: ["Potássio", "Vitamina A", "Vitamina E", "Vitamina C"],
  },
  {
    nome: "Pão",
    preco: 5,
    secao: "Panificadora",
    categoria: "Pães",
    img: "./src/img/pao.png",
    promocao: true,
    precoPromocao: "2.50",
    componentes: ["Cálcio", "Sódio", "Fibra Alimentar", "Proteínas"],
  },
  {
    nome: "Leite",
    preco: 7,
    secao: "Laticínio",
    categoria: "Leite",
    img: "./src/img/leite.png",
    promocao: false,
    precoPromocao: "1.00",
    componentes: ["Carboidratos", "Proteínas", "Gorduras totais"],
  },
  {
    nome: "Yorgut de Morango",
    preco: 3,
    secao: "Laticínio",
    categoria: "Leite",
    img: "./src/img/yogurte-morango.png",
    promocao: false,
    precoPromocao: "0",
    componentes: ["Fibras", "Vitamina C", "Cálcio", "Ferro", "Gorduras totais"],
  },
  {
    nome: "Torta de Maçã",
    preco: 7,
    secao: "Panificadora",
    categoria: "Sobremesa",
    img: "./src/img/torta-maca.png",
    promocao: true,
    precoPromocao: "1.50",
    componentes: ["Potássio", "Vitamina A", "Vitamina E", "Vitamina C"],
  },
  {
    nome: "Bolo",
    preco: 10,
    secao: "Panificadora",
    categoria: "Sobremesa",
    img: "./src/img/bolo.png",
    promocao: false,
    precoPromocao: "1.00",
    componentes: ["Carboidratos", "Proteínas", "Gorduras totais", "Fibras"],
  },
];
